"""Original starter questions for Saarthi's native mock-test experience."""

QUESTIONS = [
    {"id":"p1","subject":"Polity","q":"With reference to a Money Bill, consider the following statements:\n1. It can be introduced only in the Lok Sabha.\n2. The Rajya Sabha can reject it within fourteen days.\n3. The Speaker's certification is final.","options":["1 and 2 only","1 and 3 only","2 and 3 only","1, 2 and 3"],"answer":1,"explanation":"A Money Bill is introduced only in Lok Sabha. Rajya Sabha may recommend changes but cannot reject or amend it. The Speaker's certification is final.","source":"Constitution of India, Articles 109–110"},
    {"id":"p2","subject":"Polity","q":"Which constitutional body recommends the distribution of net tax proceeds between the Union and the States?","options":["NITI Aayog","GST Council","Finance Commission","Inter-State Council"],"answer":2,"explanation":"Article 280 provides for the Finance Commission, whose core function includes recommending vertical and horizontal tax devolution.","source":"Constitution of India, Article 280"},
    {"id":"p3","subject":"Polity","q":"The writ of quo warranto is issued primarily to:","options":["Release a person from unlawful detention","Command a public authority to perform its duty","Prevent a lower court from exceeding jurisdiction","Challenge unlawful occupation of a public office"],"answer":3,"explanation":"Quo warranto asks by what authority a person holds a substantive public office and prevents unlawful usurpation.","source":"Indian Polity — Constitutional Remedies"},
    {"id":"e1","subject":"Economy","q":"An increase in the policy repo rate, other things remaining constant, is most likely to:","options":["Reduce the cost of bank borrowing from RBI","Increase liquidity automatically","Make credit costlier and moderate aggregate demand","Directly increase government capital expenditure"],"answer":2,"explanation":"A higher repo rate raises the marginal cost of funds and generally tightens financial conditions, moderating credit growth and demand.","source":"RBI monetary policy framework"},
    {"id":"e2","subject":"Economy","q":"Which one of the following is included in the current account of India's Balance of Payments?","options":["Foreign direct investment inflows","External commercial borrowing","Export of software services","Changes in foreign exchange reserves"],"answer":2,"explanation":"Trade in goods and services, primary income and transfers form the current account. FDI and borrowing are financial-account items.","source":"Balance of Payments accounting"},
    {"id":"e3","subject":"Economy","q":"Stagflation refers to the simultaneous occurrence of:","options":["High growth and low inflation","High inflation and stagnant output","Deflation and full employment","Currency appreciation and fiscal surplus"],"answer":1,"explanation":"Stagflation combines persistent inflation with weak or stagnant economic activity, often alongside elevated unemployment.","source":"Macroeconomics — Inflation"},
    {"id":"g1","subject":"Geography","q":"Western Disturbances that affect northwestern India generally originate near the:","options":["South China Sea","Mediterranean region","Arabian Sea equator","Bay of Bengal"],"answer":1,"explanation":"Western Disturbances are extratropical systems originating around the Mediterranean-West Asian region and moving eastward with the westerlies.","source":"Indian climatology"},
    {"id":"h1","subject":"History","q":"The Permanent Settlement of 1793 was introduced primarily in:","options":["Bombay and Sind","Bengal, Bihar and Orissa","Madras Presidency","Punjab and Awadh"],"answer":1,"explanation":"Cornwallis introduced the Permanent Settlement in Bengal, Bihar and Orissa, recognising zamindars as proprietors subject to fixed revenue payment.","source":"Modern Indian History — Land revenue systems"},
    {"id":"env1","subject":"Environment","q":"The Ramsar Convention is specifically concerned with the conservation and wise use of:","options":["Tropical forests","Wetlands","Migratory birds only","World heritage monuments"],"answer":1,"explanation":"The Ramsar Convention provides the framework for conservation and wise use of wetlands and their resources.","source":"Ramsar Convention, 1971"},
    {"id":"s1","subject":"Science & Tech","q":"CRISPR-Cas9 technology is best described as a tool for:","options":["Carbon capture","Targeted genome editing","Quantum encryption","Remote sensing"],"answer":1,"explanation":"CRISPR-Cas systems can be programmed to identify and cut particular DNA sequences, enabling targeted genome editing.","source":"Biotechnology — genome editing"},
]

TESTS = [
    {"id":"polity-sectional","title":"Indian Polity — Sectional I","kind":"Sectional Mock Test","subject":"Polity","minutes":15,"question_ids":["p1","p2","p3"],"difficulty":"UPSC standard"},
    {"id":"economy-sectional","title":"Indian Economy — Sectional I","kind":"Sectional Mock Test","subject":"Economy","minutes":15,"question_ids":["e1","e2","e3"],"difficulty":"UPSC standard"},
    {"id":"full-gs-1","title":"GS Paper I — Full-Length Starter 01","kind":"Full Length Mock Test","subject":"Mixed GS","minutes":120,"question_ids":[q["id"] for q in QUESTIONS],"difficulty":"Balanced"},
    {"id":"full-gs-2","title":"GS Paper I — Full-Length Starter 02","kind":"Full Length Mock Test","subject":"Mixed GS","minutes":120,"question_ids":["env1","e2","p3","g1","s1","p1","h1","e1","p2","e3"],"difficulty":"Moderate–Hard"},
]


def questions_for(test: dict) -> list[dict]:
    lookup = {q["id"]: q for q in QUESTIONS}
    return [lookup[qid] for qid in test["question_ids"]]
